version: 2.1

orbs:
  python: circleci/python@1.4.0
 
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    working_directory: ~/flask-docker-kn/app
    steps:
      - checkout
        path: ~/flask-docker-kn
      - run: pip install flask
  
  test:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    working_directory: ~/flask-docker-kn/app
    steps:
      - checkout
        path: ~/flask-docker-kn
      - run: pip install flask
      - run: 
          name: test 
          command: exec python flask-test.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build